#ifndef EMPERY_CENTER_MSG_ERR_DUNGEON_HPP_
#define EMPERY_CENTER_MSG_ERR_DUNGEON_HPP_

#include <poseidon/cbpp/status_codes.hpp>

namespace EmperyCenter {

namespace Msg {
	using namespace Poseidon::Cbpp::StatusCodes;

	enum {
		ERR_NO_SUCH_DUNGEON_ID                  = 72501,
		ERR_DUNGEON_PREREQUISITE_NOT_MET        = 72502,
		ERR_DUNGEON_DISPOSED                    = 72503,
		ERR_DUNGEON_TOO_FEW_SOLDIERS            = 72504,
		ERR_DUNGEON_TOO_MANY_SOLDIERS           = 72505,
		ERR_BATTALION_TYPE_FORBIDDEN            = 72506,
		ERR_BATTALION_NOT_IDLE                  = 72507,
		ERR_DUNGEON_NO_BATTALIONS               = 72508,
		ERR_DUNGEON_TOO_MANY_BATTALIONS         = 72509,
		ERR_NO_SUCH_DUNGEON                     = 72510,
		ERR_NO_SUCH_DUNGEON_OBJECT              = 72511,
		ERR_DUNGEON_SERVER_CONFLICT             = 72512,
		ERR_NOT_IN_DUNGEON                      = 72513,
		ERR_NO_DUNGEON_SERVER_AVAILABLE         = 72514,
		ERR_DUNGEON_SERVER_CONNECTION_LOST      = 72515,
		ERR_NOT_YOUR_DUNGEON_OBJECT             = 72516,
		ERR_NOT_MOVABLE_DUNGEON_OBJECT          = 72517,
		ERR_NO_SUCH_DUNGEON_OBJECT_TYPE         = 71518,
		ERR_DUNGEON_WAIT_CONTEXT_INVALID        = 71519,
		ERR_FAIL_SEARCH_TARGE                   = 72520,
		ERR_DUNGEON_SUSPENDED                   = 71521,
		ERR_DUNGEON_NOT_SUSPENDED               = 72522,
		ERR_NO_DUNGEON_CELL                     = 72523,
		ERR_NO_DUNGEON_TRAP_DATA                = 72524,
		ERR_NO_DUNGEON_TRAP_IN_POS              = 72525,
		ERR_BLOCKED_BY_TRIGGER_BLOCK_POINT      = 72526,
		ERR_NO_DUNGEON_BUFF_DATA                = 72527,
		ERR_NO_DUNGEON_BUFF_IN_POS              = 72528,
		ERR_ZERO_DUNGEON_OBJECT_ATTACK          = 72529,
		ERR_BLOCKED_BY_TRIGGER_BLOCKS           = 72530,
		ERR_DUNGEON_ALREADY_BEGIN               = 72531,
		ERR_DUNGEON_MONSTER_DECORATE_AI         = 72532,
		ERR_DUNGEON_NEED_TASK_NOT_REWARD        = 72533,
		ERR_DUNGEON_OFFLINE_HAVE_FAILED         = 72534,
		ERR_DUNGEON_NOT_ENOUGH_BATTALION        = 72535,
		ERR_DUNGEON_BATTALION_HAVE_CREATED      = 72536,
	};
}

}

#endif
